services:
  ros:
    build: .
    container_name: ros_noetic
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
      - DISPLAY=$DISPLAY
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /dev/dri:/dev/dri
      - /dev/nvidia0:/dev/nvidia0
      - /dev/nvidia-uvm:/dev/nvidia-uvm
      - /dev/nvidia-uvm-tools:/dev/nvidia-uvm-tools
      - /dev/nvidiactl:/dev/nvidiactl
      - .vscode:/root/catkin_ws/.vscode
      # for the homework
      # - ./hw_1/src:/root/catkin_ws/src # this part is for homework 1
      - ./hw_2/src:/root/catkin_ws/src # this part is for homework 2
    devices:
      - /dev/nvidia0:/dev/nvidia0
      - /dev/nvidia-uvm:/dev/nvidia-uvm
      - /dev/nvidia-uvm-tools:/dev/nvidia-uvm-tools
      - /dev/nvidiactl:/dev/nvidiactl
    # command: /bin/zsh -c "source /opt/ros/noetic/setup.bash && /bin/zsh"
    stdin_open: true
    tty: true
    network_mode: host
    privileged: true
